name: inldsevak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.9+10

environment:
  sdk: ^3.8.1

dependencies:
  animated_custom_dropdown: ^3.1.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  file_picker: ^10.3.3
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  mobile_scanner: ^3.5.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_rating_stars: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  pinput: ^5.0.1
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  readmore: ^3.0.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  http: ^1.2.2
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  youtube_player_flutter: ^9.1.2
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/navigation_icons/
    - assets/banners/
    - assets/logo/
    - assets/profile_icons/
    - assets/emergency_icons/
    - assets/quick_access/
    - assets/placeholders/
    - assets/donations/
    - assets/lok_varta/

  fonts:
    - family: Afacad
      fonts:
        - asset: assets/fonts/Afacad-Bold.ttf
        - asset: assets/fonts/Afacad-Medium.ttf
        - asset: assets/fonts/Afacad-Regular.ttf
        - asset: assets/fonts/Afacad-SemiBold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/sevak.png"
  min_sdk_android: 21
  remove_alpha_ios: true
